jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            pattern: ".*"
            permissions:
              - "Overall/Administer"
            assignments:
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            pattern: ".*"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Read"
              - "View/Read"
            assignments:
              - "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            pattern: ".*"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Configure"
              - "Job/Read"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Create"
              - "Job/Cancel"
              - "View/Read"
            assignments:
              - "vaugie_g"
          - name: "assist"
            description: "Assistants"
            pattern: ".*"
            permissions:
              - "Overall/Read"
            assignments:
              - "nasso"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "chocolateen"
        name: "Hugo"
        password: ${USER_CHOCOLATEEN_PASSWORD}
      - id: "vaugie_g"
        name: "Garance"
        password: ${USER_VAUGIE_G_PASSWORD}
      - id: "i_dont_know"
        name: "Jeremy"
        password: ${USER_I_DONT_KNOW_PASSWORD}
      - id: "nasso"
        name: "Nassim"
        password: ${USER_NASSO_PASSWORD}

jobs:
  - file: /var/jenkins_home/job_dsl.groovy
